package logo

// pour chaque primitive (cle = nom FR), les quelques "voir aussi" de l'aide
// on vise le contraire (BC/LC) ou le plus courant, pas tout le voisinage
var voirAussi = map[string][]string{
	// deplacements et tortue
	"AVANCE":           {"RECULE"},
	"RECULE":           {"AVANCE"},
	"TOURNEDROITE":     {"TOURNEGAUCHE"},
	"TOURNEGAUCHE":     {"TOURNEDROITE"},
	"CAP":              {"FCAP"},
	"FCAP":             {"CAP"},
	"POS":              {"FPOS", "XCOR", "YCOR"},
	"FPOS":             {"POS", "FXY"},
	"XCOR":             {"YCOR", "POS"},
	"YCOR":             {"XCOR", "POS"},
	"DISTANCE":         {"VERSCAP", "POS"},
	"CERCLE":           {"ARC", "REPETE"},
	"ARC":              {"CERCLE"},
	"FIXETAILLECRAYON": {"FCC", "BC"},
	"REMPLIS":          {"FCR", "CR", "FCC"},
	"ETIQUETTE":        {"ECRIS", "FCC"},
	"ORIGINE":          {"VE", "FPOS"},
	"MT":               {"CT"},
	"CT":               {"MT"},
	"VISIBLE?":         {"MT", "CT"},
	"FIXETORTUE":       {"TORTUE", "NBTORTUES", "DEMANDE"},
	"TORTUE":           {"FIXETORTUE", "NBTORTUES"},
	"NBTORTUES":        {"FIXETORTUE", "DISTORTUE"},
	"DEMANDE":          {"FIXETORTUE", "TORTUE"},
	"DISTORTUE":        {"FIXETORTUE", "NBTORTUES"},
	"COLLISION?":       {"FIXETORTUE", "VISIBLE?"},
	"ANIME":            {"STOPANIME", "CADENCE", "COLLISION?"},
	"STOPANIME":        {"ANIME"},
	"CADENCE":          {"ANIME"},
	"SPRITE":           {"DEFSPRITE", "MT"},
	"DEFSPRITE":        {"SPRITE"},

	// crayon et couleurs
	"BC":   {"LC"},
	"LC":   {"BC"},
	"BC?":  {"BC", "LC"},
	"CC":   {"FCC"},
	"FCC":  {"CC", "FCFG"},
	"CF":   {"FCFG"},
	"FCFG": {"CF", "FCC"},
	"FCR":  {"CR", "REMPLIS", "FCC"},
	"CR":   {"FCR", "REMPLIS"},

	// ecran et champ
	"VE":      {"NETTOIE", "ORIGINE"},
	"NETTOIE": {"VE"},
	"CLOS":    {"ENR", "FEN"},
	"ENR":     {"CLOS", "FEN"},
	"FEN":     {"CLOS", "ENR"},

	// texte
	"ECRIS":  {"TAPE", "MONTRE"},
	"TAPE":   {"ECRIS", "MONTRE"},
	"MONTRE": {"ECRIS", "TAPE"},
	"FCT":    {"FCFT", "VT"},
	"FCFT":   {"FCT"},
	"VT":     {"FCURS", "ME"},
	"FCURS":  {"ME", "VT"},
	"ME":     {"FCURS", "VT"},

	// logique et controle
	"VRAI":         {"FAUX"},
	"FAUX":         {"VRAI"},
	"ET":           {"OU", "NON"},
	"OU":           {"ET", "NON"},
	"NON":          {"ET", "OU"},
	"SI":           {"SISINON", "TANTQUE", "STOP"},
	"SISINON":      {"SI", "TESTE", "STOP"},
	"REPETE":       {"REPETEPOUR", "TANTQUE", "COMPTEUR"},
	"REPETEPOUR":   {"REPETE", "POURCHAQUE"},
	"COMPTEUR":     {"REPETE"},
	"POURCHAQUE":   {"APPLIQUE", "FILTRE", "REPETEPOUR"},
	"APPLIQUE":     {"FILTRE", "REDUIS", "POURCHAQUE"},
	"FILTRE":       {"APPLIQUE", "REDUIS", "POURCHAQUE"},
	"REDUIS":       {"APPLIQUE", "FILTRE"},
	"PIEGE":        {"LANCE"},
	"LANCE":        {"PIEGE"},
	"TESTE":        {"SIVRAI", "SIFAUX", "SI"},
	"SIVRAI":       {"TESTE", "SIFAUX"},
	"SIFAUX":       {"TESTE", "SIVRAI"},
	"TANTQUE":      {"REPETE", "SI"},
	"SCENE":        {"NETTOIE", "ATTENDS"},
	"STOP":         {"RENDS", "SI"},
	"RENDS":        {"STOP"},
	"EXECRESULTAT": {"EXEC"},
	"DONNEPROP":    {"PROP", "EFPROP", "LISTEPROP"},
	"PROP":         {"DONNEPROP", "EFPROP", "LISTEPROP"},
	"EFPROP":       {"DONNEPROP", "PROP", "LISTEPROP"},
	"LISTEPROP":    {"DONNEPROP", "PROP", "EFPROP"},
	"DEFINIS":      {"TEXTE", "POUR"},
	"TEXTE":        {"DEFINIS", "IM"},

	// variables et procedures
	"DONNE":  {"CHOSE", "LOCAL"},
	"CHOSE":  {"DONNE"},
	"LOCAL":  {"DONNE", "POUR"},
	"POUR":   {"FIN", "ED"},
	"FIN":    {"POUR"},
	"ED":     {"POUR", "RAMENE"},
	"EFP":    {"EFN", ".EFT", "DETRUIS"},
	"EFN":    {"EFP", ".EFT"},
	".EFT":   {"EFP", "EFN"},
	"IM":     {"IMNS", "IMTOUT"},
	"IMNS":   {"IM", "IMTOUT"},
	"IMTOUT": {"IM", "IMNS"},

	// listes et mots
	"PREM":   {"DER", "SP", "SD"},
	"DER":    {"PREM", "SP", "SD"},
	"SP":     {"SD", "PREM", "DER"},
	"SD":     {"SP", "PREM", "DER"},
	"MOT":    {"PHRASE", "LISTE"},
	"PHRASE": {"MOT", "LISTE"},
	"LISTE":  {"MOT", "PHRASE"},
	"PIOCHE": {"ITEM", "HASARD", "COMPTE"},

	// chaines : recherche, decoupe, nettoyage
	"MEMBRE":       {"SOUSCHAINE?", "MEMBRE?", "ITEM"},
	"SOUSCHAINE?":  {"MEMBRE", "MEMBRE?"},
	"AVANT?":       {"EGAL?", "TRIE"},
	"DECOUPE":      {"MOT", "PHRASE", "TRANCHE"},
	"ROGNE":        {"ROGNEDEBUT", "ROGNEFIN"},
	"ROGNEDEBUT":   {"ROGNE", "ROGNEFIN"},
	"ROGNEFIN":     {"ROGNE", "ROGNEDEBUT"},
	"SUBSTITUE":    {"MEMBRE", "MOT"},
	"OTETOUT":      {"SANSDOUBLONS", "MEMBRE?"},
	"SANSDOUBLONS": {"OTETOUT", "TRIE"},
	"TRANCHE":      {"ITEM", "PREM", "DER", "DECOUPE"},
	"REMPLACE":     {"AJOUTE", "ITEM", "TRANCHE"},
	"AJOUTE":       {"REMPLACE", "MP", "MD"},
	"OTE":          {"TRANCHE", "OTETOUT", "SUBSTITUE"},
	"POSITION":     {"MEMBRE", "SOUSCHAINE?", "ITEM"},

	// tableaux, piles et files
	"TABLEAU":          {"FIXEITEM", "ITEM", "LISTEVERSTABLEAU", "TABLEAU?"},
	"TABLEAUMD":        {"TABLEAU", "FIXEITEMMD", "ITEMMD"},
	"LISTEVERSTABLEAU": {"TABLEAUVERSLISTE", "TABLEAU"},
	"TABLEAUVERSLISTE": {"LISTEVERSTABLEAU", "TABLEAU"},
	"ITEMMD":           {"FIXEITEMMD", "ITEM", "TABLEAUMD"},
	"FIXEITEM":         {"ITEM", "TABLEAU", "COPIETABLEAU"},
	"FIXEITEMMD":       {"ITEMMD", "TABLEAUMD", "FIXEITEM"},
	"TABLEAU?":         {"TABLEAU", "LISTE?", "MOT?"},
	"COPIETABLEAU":     {"TABLEAU", "FIXEITEM"},
	"EMPILE":           {"DEPILE", "ENFILE", "MP"},
	"DEPILE":           {"EMPILE", "DEFILE", "PREM"},
	"ENFILE":           {"DEFILE", "EMPILE", "MD"},
	"DEFILE":           {"ENFILE", "DEPILE", "PREM"},

	// nombres
	"SOMME":      {"DIFF", "PROD", "DIV"},
	"DIFF":       {"SOMME"},
	"PROD":       {"DIV", "SOMME"},
	"DIV":        {"PROD", "QUOT", "RESTE"},
	"QUOT":       {"DIV", "RESTE"},
	"RESTE":      {"DIV", "QUOT"},
	"ARRONDI":    {"TRONQUE", "ENT"},
	"TRONQUE":    {"ARRONDI", "ENT"},
	"ENT":        {"ARRONDI", "TRONQUE"},
	"SIN":        {"COS", "TANGENTE", "ARCTAN"},
	"COS":        {"SIN", "TANGENTE", "ARCTAN"},
	"TANGENTE":   {"SIN", "COS", "ARCTAN"},
	"ARCTAN":     {"TANGENTE", "SIN", "COS"},
	"VALABS":     {"ARRONDI", "TRONQUE"},
	"MODULO":     {"RESTE", "DIV"},
	"MAJUSCULE":  {"MINUSCULE", "MOT"},
	"MINUSCULE":  {"MAJUSCULE", "MOT"},
	"VERSCAP":    {"FCAP", "CAP"},
	"FXY":        {"FPOS", "POS"},
	"EXP":        {"LN", "LOG10", "PUISSANCE"},
	"LN":         {"EXP", "LOG10"},
	"LOG10":      {"LN", "EXP"},
	"TRIE":       {"INVERSE", "ITEM", "ORDONNE"},
	"ORDONNE":    {"TRIE", "TABLEAU", "FIXEITEM"},
	"OUEX":       {"ET", "OU", "RESTE"},
	"VERSBASE":   {"DEPUISBASE", "HEXA", "BINAIRE"},
	"DEPUISBASE": {"VERSBASE", "HEXA", "BINAIRE"},
	"HEXA":       {"BINAIRE", "VERSBASE", "DEPUISBASE"},
	"BINAIRE":    {"HEXA", "VERSBASE", "DEPUISBASE"},

	// clavier et souris
	"LISCAR":        {"LL", "LISMOT", "TOUCHE?"},
	"LL":            {"LISCAR", "LISMOT", "TOUCHE?"},
	"LISMOT":        {"LL", "LISCAR", "TOUCHE?"},
	"TOUCHE?":       {"LISCAR", "LL"},
	"LIS":           {"LL", "LISMOT", "LISCAR"},
	"SOURISPOS":     {"SOURISPRESSEE"},
	"SOURISPRESSEE": {"SOURISPOS"},
	"MANETTE":       {"BOUTON?"},
	"BOUTON?":       {"MANETTE"},

	// fichiers
	"SAUVEPNG":  {"SAUVE", "CATALOGUE"},
	"SAUVE":     {"RAMENE", "CHARGE", "CATALOGUE"},
	"RAMENE":    {"SAUVE", "CHARGE"},
	"CHARGE":    {"SAUVE", "RAMENE"},
	"SAUVED":    {"SAUVE", "CHARGE"},
	"CATALOGUE": {"SAUVE", "DETRUIS"},
	"DETRUIS":   {"CATALOGUE", "EFP"},

	// fichiers de donnees (flux)
	"OUVRELECTURE":       {"FIXELECTURE", "FERME", "LISLIGNE"},
	"OUVREECRITURE":      {"FIXEECRITURE", "FERME", "OUVREAJOUT"},
	"OUVREAJOUT":         {"OUVREECRITURE", "FIXEECRITURE", "FERME"},
	"OUVREMAJ":           {"OUVRELECTURE", "OUVREECRITURE", "POSLECTURE"},
	"FERME":              {"FERMETOUT", "OUVRELECTURE", "TOUSOUVERTS"},
	"FERMETOUT":          {"FERME", "TOUSOUVERTS"},
	"TOUSOUVERTS":        {"FERME", "FERMETOUT"},
	"FIXELECTURE":        {"OUVRELECTURE", "FLUXLECTURE", "LISLIGNE"},
	"FIXEECRITURE":       {"OUVREECRITURE", "FLUXECRITURE", "ECRIS"},
	"FLUXLECTURE":        {"FIXELECTURE", "FLUXECRITURE"},
	"FLUXECRITURE":       {"FIXEECRITURE", "FLUXLECTURE"},
	"FINFICHIER?":        {"LISLIGNE", "FIXELECTURE", "LISCAR"},
	"POSLECTURE":         {"FIXEPOSLECTURE", "POSECRITURE"},
	"POSECRITURE":        {"FIXEPOSECRITURE", "POSLECTURE"},
	"FIXEPOSLECTURE":     {"POSLECTURE", "FIXEPOSECRITURE"},
	"FIXEPOSECRITURE":    {"POSECRITURE", "FIXEPOSLECTURE"},
	"LISLIGNE":           {"FIXELECTURE", "FINFICHIER?", "LISCARS"},
	"LISCARS":            {"LISLIGNE", "LISCAR", "FIXELECTURE"},
	"FICHIERVERSTABLEAU": {"LISLIGNE", "TABLEAU", "COMPTE"},

	"CATALOGUEEX": {"CATALOGUE", "RAMENEEX", "CHARGEEX"},
	"RAMENEEX":    {"RAMENE", "CATALOGUEEX", "CHARGEEX"},
	"CHARGEEX":    {"CHARGE", "CATALOGUEEX", "RAMENEEX"},

	// son
	"JOUE":   {"OCTAVE", "DUREE", "TEMPO", "TIMBRE"},
	"OCTAVE": {"JOUE", "DUREE", "TEMPO"},
	"DUREE":  {"JOUE", "TEMPO", "OCTAVE"},
	"TEMPO":  {"JOUE", "DUREE"},
	"TIMBRE": {"JOUE"},
}
